### PR TITLE
Make the person name visible in edit view if already set.

### PR DESCRIPTION
**Pull request by rbalekai**
Fixes ndlib/planning#254

### CODE REVIEW

**Comment by jcoyne** [comment]
Tests are not running

**Comment by jcoyne** [comment]
Oops, looks like that was due to https://github.com/ndlib/curate/pull/179

**Comment by jcoyne** [comment]
Does this need a test? I don't see how ndlib/planning#254 was fixed.

**Comment by jeremyf** [comment]
Yes. This needs a test.

**Comment by jcoyne** [comment]
Please squash these two commits together now.

**Comment by jeremyf** [comment]
@rbalekai Instead of a Capybara test, please write a unit test on Account. Those typically run faster.

**Pull request merged**
