### PR TITLE
Changes button_to to link_to in collections_helper.

### PR DESCRIPTION
**Pull request by scherztc**
We changed the button_to to a link_to on the
actions_for_member method.  We were experiencing
problems with the confirmation and turbo links
when using the button_to.

### CODE REVIEW

**Comment by jeremyf** [comment]
:+1: Assuming the build passes.

**Comment by scherztc** [comment]
We got some failing test on our curate/develop branch that I branched.  I will look into them.

**Comment by scherztc** [comment]
@jeremyf @rbalekai .  
I have all the test passing but one type.  The last one that I am having a problem with is:

spec/features/user_profile_workflow_spec.rb:75 
#user profile workflow when I have not yet logged into Curate 

Failure/Error: within("form.new_user") do
     Capybara::ElementNotFound:
       Unable to find css "form.new_user"

Test pass with Devise version 3.2.4 but fail with Devise 3.3.0.   Any ideas?
I thought it might be related to : @@expire_all_remember_me_on_sign_out = true???

**Comment by scherztc** [comment]
I think I know what is going on.  From version 3.2.4 to version 3.3.0 of Devise they added a validator in the new method of the registration controller:

 @validatable = devise_mapping.validatable?
    if @validatable
      @minimum_password_length = resource_class.password_length.min
    end

Since we overwrite resource_class to the object: Account in curate, it can't find the password_length method in our model.  Therefore we are getting a 500 error our feature test are failing.  Should I add a password_length method to our Account model?  What should that method look like?

**Comment by jeremyf** [comment]
@scherztc 

This is all that we have, and things appear to be working. If that is not the case, you would need to a class method `.password_length`.

``` console
curate/app/models/curate/devise_user_shim.rb:
   47        end
   48  
   49:       def password_length
   50:         wrapped_class.password_length
   51        end
   52  

curate/spec/internal/config/initializers/devise.rb:
  141    # ==> Configuration for :validatable
  142    # Range for password length.
  143:   config.password_length = 8..128
  144  
  145    # Email regex used to validate email formats. It simply asserts that
```

**Comment by scherztc** [comment]
Thanks for the tip.  Test passing with latest Devise gem.

**Pull request merged**
