### PR TITLE
Incorporate omniauth for flexible authenticaiton.

### PR DESCRIPTION
**Pull request by rbalekai**
This will require that the application will configure the providers information.

For Example:
config.omniauth :twitter, 'consumer_key', 'consumer_secret'
config.omniauth :cas, host: 'host_name', login_url: '/cas/login', service_validate_url: '/cas/serviceValidate'

in devise.rb

HYDRASIR-51 #close

### CODE REVIEW

**Comment by jcoyne** [comment]
:-1: Don't put Omniauth in curate.  Omniauth is for multiple auth providers.  None of the curate institutions needs more than one provider.

**Comment by jeremyf** [comment]
@jcoyne the authentication structure that we will likely be moving towards is:
- I create an account in Curate via my institutions authentication system
- I authorize ORCID, Twitter, Google, etc as a system I can use for authentication of my Curate account

I am then able to sign in either via institution authentication or ORCID.

**Comment by jcoyne** [comment]
This seems like a low value / high cost feature.  But if that's how it's going to be done you'll need Omni-auth.  Keep in mind we need to remove all "password" stuff from curate, because you won't have a password for some auth providers.

**Comment by jeremyf** [comment]
@jcoyne - We are discussing the idea of stripping out authentication and registration into a separate engine. The engine would need to expose to the containing application the basic methods that Rails expects as a convention (i.e. `current_user`, `logged_in?`, etc.) @dbrower has a list of the four methods required to implement the public API of a Devise application)

**Comment by jcoyne** [comment]
@jeremyf I like that idea better.  That is what blacklight does too.

**Comment by mstroming** [comment]
Hi all, this is a good discussion. Some questions...

What are the benefits in moving the auth to another engine?

Shouldn't Curate at least come with the ability to authenticate against LDAP, Shibboleth, etc with configuration changes? Forcing the implementers to do all of that work when we can do most of it up front is valuable, right?

**Comment by jcoyne** [comment]
Authenticating against ldap is something that devise_ldap_authenticatable
gem is very good at, but it's extra code (read: less secure and harder to
maintain) for the users who only want Shibboleth.  Furthermore, all LDAP
are not created equal.  As an example, some institutions can use LDAP to
authenticate users (Northwestern?) while others use a SSO but still rely on
LDAP for group authorization (Penn State).

It is in everyones best interest that we concentrate on the shared reusable
components, not on the differences in every institutions authn/authz
solution.

-Justin

**Comment by mstroming** [comment]
@jcoyne Thanks, those are good points. Without much work, though, I think Curate can let folks choose from LDAP, CAS and Shibboleth by making config changes? Maybe we should just document the different approaches?

**Comment by jeremyf** [comment]
@rbalekai I'm going to close this pull request; and we'll see if its something to bring in later.

For now, we'll push the "flexible authentication" down to the Curate-based application implementation.

**Comment by rbalekai** [comment]
so how does that affect https://jira.duraspace.org/browse/HYDRASIR-11?

**Pull request closed without merging**
