### PR TITLE
Adding `spec:show_matchers` rake task

### PR DESCRIPTION
**Pull request by jeremyf**
Sample output (note the paths were truncated)

```
have_exactly           rspec-expectations-2.14.4/lib/rspec/matchers.rb:444
have_form              rspec-html-matchers-0.4.3/lib/rspec-html-matchers.rb:303
have_multivalue_field  curate/spec/support/matchers/metadata_field_matchers.rb:19
```

### CODE REVIEW

**Comment by jcoyne** [comment]
Why is this necessary? Is Curate the best location for this?

**Comment by jeremyf** [comment]
This is helpful for other developers to know what shared matchers exist and where to find them. @danhorst asked me "Where are all the matchers?" and I honestly couldn't tell him how to reliably find them all. I'm especially looking at new developers coming on for Curate and looking to provide them with tooling to help them find things.

One of the challenges I ran into was that I really wanted to lean on loading `spec_helper.rb` to ensure all matchers were loaded; But that proved to be a path of extreme pain (`Devise` kept want to say it wasn't defined).

A more generalized solution could theoretically be extracted and packaged up. Likewise a single file responsible for requiring all of the applications rspec matchers would help to eliminate some of the duplicate code.

**Comment by danhorst** [comment]
:+1: I was looking for a way to find the "best" matchers for while refactoring some tests. There doesn't appear to be a way to list all the available matchers without implementing something like this.

**Comment by jcoyne** [comment]
What about the matchers in `rspec/rails/matchers/*` does it pick those up?  Or 
Capybara::RSpecMatchers or Webrat::Matchers?

**Comment by jeremyf** [comment]
@jcoyne It is missing rspec-rails; I'm going to tweak this a bit.

**Comment by jcoyne** [comment]
I'm wondering if you want to search the ObjectSpace like this:

```
ObjectSpace.each_object(Class).select { |klass| klass < RSpec::Matchers::BuiltIn::BaseMatcher }
```

Of course, you'd need to make sure the ones we use are required first.

**Comment by jeremyf** [comment]
@jcoyne One of the challenges is that the BaseMatcher does not reflect the method name used; It appears the convention is that you add instance methods to a module to represent the matcher.

**Comment by jeremyf** [comment]
@jcoyne I've reworked the behavior by including a "spec/matchers.rb" file that is responsible for the include logic for matchers.

**Comment by jeremyf** [comment]
@danhorst would you care to merge?

**Pull request merged**
