### PR TITLE
Sender field should include user netid.

### PR DESCRIPTION
**Pull request by rbalekai**

### CODE REVIEW

**Comment by rbalekai** [comment]
The email ID in the from field will be one of User netID or default Email ID

The email ID in the body will be user's optional email ID or user's netid.

**Comment by jeremyf** [comment]
The builds fail, please squash into one commit.

**Comment by jeremyf** [comment]
The build is still breaking; Please review the broken build. Then rebase all of the commits into a single commit: see 
http://ndlib.github.io/practices/one-commit-per-pull-request/

**Comment by jeremyf** [comment]
@rbalekai The build is broken and my local tests fail.

**Pull request merged**
