### PR TITLE
Interrogating Person for User attributes

### PR DESCRIPTION
**Pull request by jeremyf**
Given that every User has a Person
And not every Person has a User
And we want to expose via the UI the ability to update a User's person
When the User is created or updated
Then a Person should be created with the attributes that were set for
  the user

### CODE REVIEW

**Comment by flyingzumwalt** [comment]
I'm not sure that I understand these changes.  Can someone else review & merge?

Do we have an option to roll back master for now and defer this refactor until after the sprint is over?

**Comment by val99erie** [comment]
Where do the Person.registered_attribute_names get defined?

**Comment by danhorst** [comment]
@val99erie https://github.com/ndlib/curate/commit/790fb3a11e610a4c223804844e897d057c3288c7#L2R14

Wait. That wasn't it exactly.

**Comment by jeremyf** [comment]
This is growing into a bigger problem as I'm delving into things. Which means I'm going to back out the commits on master that are related to this.

**Pull request closed without merging**
