### PR TITLE
Show page should have a preview of the representative file

### PR DESCRIPTION
**Pull request by jcoyne**
If the representative file is an audio file, show an audio player

### CODE REVIEW

**Comment by jeremyf** [comment]
I'm reviewing this pull request locally.

**Comment by jeremyf** [comment]
Still reviewing; Haven't had much time.

I'm assuming this is something we want. @danhorst

**Comment by danhorst** [comment]
:+1: I like where this is headed. @jcoyne were you planning on bringing in [videojs](https://github.com/videojs/video.js/) as well or are we just relying on native HTML5 audio playback for now?

**Comment by jcoyne** [comment]
@danhorst Yeah, just HTML5 for now. I figure video.js would be a good add on.  Sufia encorporates it: https://github.com/projecthydra/sufia/blob/95b02b8c5d567049658ede1dcee2911afe3585e7/app/assets/stylesheets/sufia.css.scss#L9

**Pull request merged**
