### PR TITLE
Writing code standards/guidelines

### PR DESCRIPTION
**Pull request by jeremyf**
HYDRASIR-63 #close Writing code standards/guidelines

https://jira.duraspace.org/secure/RapidBoard.jspa?rapidView=16&view=detail&selectedIssue=HYDRASIR-63

[skip ci]

### CODE REVIEW

**Comment by jeremyf** [comment]
Attention: @projecthydra/hydra-curate (I still need NU Paul and IU developers' github accounts)

**Comment by mark-dce** [comment]
I've run into three institutions that tried to do production installations using hydra-jetty.  You call out that jetty is used for development and testing.  It might actually be worth calling out that the hydra-jetty package should not be use for secure production installations.

**Comment by jeremyf** [comment]
@mark-dce I amended the commit to include your language.

**Comment by spr7b** [comment]
+1  Standards look good/reasonable.

**Comment by hortongn** [comment]
:+1: Coding Guidelines look good

**Comment by mark-dce** [comment]
Thanks!

+1 on the overall guidelines

**Comment by nomadicoder** [comment]
+1 Looks good.

**Pull request merged**
