### PR TITLE
Create a persisted organization model

### PR DESCRIPTION
**Pull request by rbalekai**
HYDRASIR-97 #close

### CODE REVIEW

**Comment by rbalekai** [comment]
Dont merge it yet. The implementation is not complete.

**Comment by jcoyne** [comment]
Can this be rebased so it doesn't have the "fixing merge" commits.

**Comment by jeremyf** [comment]
I'm assigning this to @rbalekai to rebase this pull request when it is ready for merging.

It also looks like we need to have some guidance on how to share work on a branch without submitting a pull request; But that may not be the case for this.

**Comment by spr7b** [comment]
I think I just closed that pull request for the organization work.  I think it got created in error yesterday and got left there.

**Pull request closed without merging**
