### PR TITLE
Expand Rails gem to be ~> 4.0.0

### LINKED ISSUE #303: Expand Rails gem to be ~> 4.0.0
Instead of locking `gem 'rails', '4.0.0'` set it to `gem 'rails', '~> 4.0.0'`

There is a pull request related to this, but at one point the tests were failing.

### PR DESCRIPTION
**Pull request by scherztc**
Fixes #298, Fixes #303

### CODE REVIEW

**Comment by jeremyf** [comment]
@scherztc Its looking like non-persisted Person objects are creating some of the issues.

Have you been able to get tests running locally? They are slow, and my next week's goal is to speed them up considerably.

**Comment by scherztc** [comment]
Jeremy,

Be patient with me as I learn.
1.  When I ran the "rspec spec" locally,  the first error message I got was:

/Users/thomasscherz/Workspace/curate/spec/internal/config/initializers/devise.rb:3:in `<top (required)>': uninitialized constant Devise (NameError)
1.  When I started the rails server from /spec/internal I got the following error message when I browsed http://localhost:3000

WebMock::NetConnectNotAllowedError in CatalogController#index
Real HTTP connections are disabled. Unregistered request: GET http://localhost:8983/solr/development/select?
I got both of these message regardless of which branch I was in 'master' or 'expand_rails_gem'.

Where should I look next to resolve?

Thanks.

Thomas

On Nov 13, 2013, at 3:53 PM, Jeremy Friesen <notifications@github.com<mailto:notifications@github.com>> wrote:

@scherztchttps://github.com/scherztc Its looking like non-persisted Person objects are creating some of the issues.

Have you been able to get tests running locally? They are slow, and my next week's goal is to speed them up considerably.

**Comment by jeremyf** [comment]
@scherztc 

Issue 1: I have a bash alias `cspec` that does the following: `BUNDLE_GEMFILE=./spec/internal/Gemfile bundle exec rspec`

Issue 2: WebMock and spec/internal are not playing well together. I believe I need to have WebMock required only for the `group: :test` in the spec/internal/Gemfile (but that is auto-generated)

**Comment by danhorst** [comment]
@scherztc the test app doesn't quite generate right. [I update mine manually](https://gist.github.com/danhorst/7473012).
We'll try to update the generator to address this eventually.

**Comment by scherztc** [comment]
1.  @jeremyf After running the cspec alias, I get a path error (right at the beginning):

generate  curate:work:with_doi
/Users/thomasscherz/Workspace/curate/spec/internal/spec/internal/Gemfile not found

Which spec file is searching for the Gemfile?
1.  Then as the test run, I get the following after hook error:

An error occurred in an after hook
  NoMethodError: undefined method `name=' for #<User:0x007fba7e986a08>
  occurred at /Users/thomasscherz/.rvm/gems/ruby-2.0.0-p247@curate/gems/activemodel-4.0.0/lib/active_model/attribute_methods.rb:436:in`method_missing'

If you get a minute later today, maybe you can walk me through running the test locally through IRC.

**Comment by jeremyf** [comment]
@scherztc Did you clone curate? If so what is the SHA1 that you are working from. Perhaps the best way to trouble shoot this is to use Google Hangouts so you can share your screen with me.

How I've usually done things is:

`rake jetty:start` followed by `rake clean generate spec`

**Comment by jeremyf** [comment]
It is also possible that you need to run curate's migrations. To find what the migration task is, run `rake -T`. This will give you a list of all rake tasks. There should be one for curate migrations.

**Comment by scherztc** [comment]
Yeah.  I cloned curate.  Here is my git log file:

commit 31bb320ca36ec9447a11e069c47e03e65245c1fe
Author: Thomas Scherz <thomas.scherz@uc.edu<mailto:thomas.scherz@uc.edu>>
Date:   Wed Nov 13 14:06:18 2013 -0500

```
Expand Rails gem to be ~> 4.0.0
```

commit 7e2c53d7446f4896d3a9d2dce153d7b10f7850d9
Author: Jeremy Friesen <jeremy.n.friesen@gmail.com<mailto:jeremy.n.friesen@gmail.com>>
Date:   Wed Nov 13 12:45:14 2013 -0500

```
Repacling simplecov with coco

[skip ci]
```

commit 1ddfe325ca6f4487c2c4c63151b753c908192c3f
Author: Jeremy Friesen <jeremy.n.friesen@gmail.com<mailto:jeremy.n.friesen@gmail.com>>
Date:   Wed Nov 13 11:16:01 2013 -0500

```
Updating engine Gemfile install to not assume directory

Given that some people may install curate in a directory not named curate, t
```

commit 32327e6b9a2de67aebc81f9f4928eefd6d3624fa

I can do a google hangout around 2:00 PM.  Gonna be around?

Thomas

On Nov 18, 2013, at 11:37 AM, Jeremy Friesen <notifications@github.com<mailto:notifications@github.com>>
 wrote:

@scherztchttps://github.com/scherztc Did you clone curate? If so what is the SHA1 that you are working from. Perhaps the best way to trouble shoot this is to use Google Hangouts so you can share your screen with me.

**Comment by jeremyf** [comment]
@scherztc Were you able to run `rake clean generate spec`

**Comment by scherztc** [comment]
1.  Yes.  I was able to run rake clean generate spec from the curate directory.

Finished in 18 minutes 15 seconds
734 examples, 1 failure, 1 pending

Failed examples:

rspec /Users/thomasscherz/Workspace/curate/spec/features/catalog_search_spec.rb:79 # Search for a work Facet - Cancel bar should display collection title and not PID
1.  When I ran the cspec alias from the curate folder I got a different result:

Finished in 15 minutes 5 seconds
783 examples, 246 failures, 1 pending

Is this consistent?

On Nov 18, 2013, at 12:20 PM, Jeremy Friesen <notifications@github.com<mailto:notifications@github.com>>
 wrote:

@scherztchttps://github.com/scherztc Were you able to run rake clean generate spec

**Comment by jeremyf** [comment]
@scherztc The catalog controller has a really erratic bug that I've been trying to track down. It seems to manifest every other time (which makes no sense to me). So, from my perspective "Things are Working"™

**Comment by hortongn** [comment]
I can confirm that with this change the local tests on my box return with
741 examples, 0 failures, 1 pending

**Comment by jeremyf** [comment]
@scherztc Go ahead and commit the local changes and rebase/squash your branch to a single commit. I assume there are some test changes you've made.

More on squashing commits (http://ndlib.github.io/practices/one-commit-per-pull-request/)

**Comment by scherztc** [comment]
@jeremyf... We made sure the repository was up to date using the following rebase commands:
$ git checkout master
$ git pull --rebase origin # The remote repo that is "origin"
$ git checkout expand_rails_gem
$ git rebase master

it passed our local spec test:

Finished in 16 minutes 52 seconds
743 examples, 0 failures, 1 pending

We only had 1 commit so we didn't need to squash.

We force pushed up the repository:
git push -f

Then we monitored Travis and Travis failed on:

No route matches {:id=>#<Person pid:"", relative_path:nil, depositor:nil, owner:nil, representative:nil, name:"User Named 9", email:nil, alternate_email:nil, date_of_birth:nil, title:nil, campus_phone_number:nil, alternate_phone_number:nil, personal_webpage:nil, blog:nil, gender:nil>} missing required keys: [:id]

Is there something we can do about this route error or is this part of the non-persisted Person object you mentioned earlier?

**Comment by jeremyf** [comment]
@scherztc What does ./spec/internal/Gemfile look like?

**Comment by scherztc** [comment]
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'

gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record

gem 'sqlite3'

# Use SCSS for stylesheets

gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets

gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views

gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes

# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library

gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks

gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder

gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password

# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server

# gem 'unicorn'

# Use Capistrano for deployment

# gem 'capistrano', group: :development

# Use debugger

# gem 'debugger', group: [:development, :test]

gem 'curate', :path=>'../../../curate'
gem 'capybara'
gem 'launchy'
gem 'factory_girl_rails'
gem 'timecop'
gem 'vcr'
gem 'webmock'
gem 'rspec-html-matchers'
gem 'database_cleaner', '< 1.1.0', :group => :test
gem 'test_after_commit', group: :test
gem 'poltergeist', group: :test
gem 'coco', group: :test, require: false
gem 'debugger'
gem 'kaminari', github: 'harai/kaminari', branch: 'route_prefix_prototype'

gem "bootstrap-sass"
gem "devise"
gem "devise-guests", "~> 0.3"
group :development, :test do
  gem "rspec-rails"
  gem "jettywrapper"
end

**Comment by scherztc** [comment]
After looking at the travis log file, I noticed that my rails gem was still at 4.0.0.  I have updated it to 4.0.1 and am running the test locally again.

**Comment by scherztc** [comment]
A few failures this time:

Finished in 16 minutes 49 seconds
743 examples, 119 failures, 1 pending

We'll talk more in the scrum tomorrow.

**Comment by hortongn** [comment]
I can confirm that this branch has multiple test failures when I'm running rails 4.0.1 even though everything passed under 4.0.0.  So rails 4.0.1 definitely introduces some problems.

**Pull request closed without merging**
