### PR TITLE
Adding Group to GenericWork should work

### PR DESCRIPTION
**Pull request by rbalekai**
There is no jira ticket for this.

### CODE REVIEW

**Comment by scherztc** [comment]
I downloaded your branch locally and ran the test.  
I got 834 examples, 22 failures, 2 pending

I understand what you did.  Not sure why though.

**Comment by scherztc** [comment]
My failures are probably due to my ClamAV configuration.  Checking into it.

**Comment by scherztc** [comment]
+1.  My local tests are now passing on this branch also.

**Comment by jcoyne** [comment]
I think #522 largely obviates this patch

**Comment by rbalekai** [comment]
I will make another PR which address this issue.

**Pull request closed without merging**
