### PR TITLE
Add rspec:install to application template

### PR DESCRIPTION
**Pull request by hortongn**
Have the application template run 'generate rspec:install' and
insert "require 'rspec/autorun'" into the spec/spec_helper.rb file
so the application is ready for the user to test any customizations.

HYDRASIR-81 #close

### CODE REVIEW

**Comment by jcoyne** [comment]
I'm not certain that we ought to force rspec on someone.  Perhaps they like minitest better.

**Comment by scherztc** [comment]
Glen,

Why don't we do a "Would you like to use rspec?"  prompt?  Similar to what is done with jetty wrapper.

Thomas

On Jan 6, 2014, at 11:03 AM, Justin Coyne <notifications@github.com<mailto:notifications@github.com>>
 wrote:

I'm not certain that we ought to force rspec on someone. Perhaps they like minitest better.

**Comment by hortongn** [comment]
We could possibly have the application template let the user choose if they want to use rspec or not.  The story for this task says "The application template will automatically run the rspec:install."  So I took that to mean that rspec should be used without prompting the user.  We'll see what @jeremyf thinks.

**Comment by jeremyf** [comment]
@hortongn I think having the prompt "Would you like to install RSpec for testing your Curate based application?" would be a good compromise.

**Pull request merged**
